### ISSUE TITLE
Should This Repository Be Archived?

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-erc20-multi#15]

**Comment by jimmychu0807** [comment]
@gautamdhameja we want to only keep projects we actively maintain under substrate-developer-hub and archive the rest. We are discussing if we should archive this project. I see you were the previous owner of the project. If you want, we can also transfer the ownership back to you. 

Otherwise, I am fine to archive this project.

**Comment by gautamdhameja** [comment]
Yeah, please go ahead and archive it. Thanks.
